/**
 * @file bootloader_public_key.c
 * @brief Embedded Ed25519 public key for firmware verification
 * @generated 2026-04-19T08:56:57.236717
 * 
 * DO NOT EDIT - Generated by sign_firmware.py
 * This key is used by the secure bootloader to verify firmware signatures.
 */

#include <stdint.h>

/* Ed25519 public key - 32 bytes */
const uint8_t EMBEDDED_PUBLIC_KEY[32] = {
    0x07, 0xB7, 0x08, 0x2A, 0x5E, 0x0A, 0xBE, 0x14, 0x19, 0x88, 0x0A, 0x17, 0xB4, 0x26, 0xCE, 0x91, 0x58, 0xDC, 0x55, 0xE0, 0x81, 0x4A, 0x0C, 0xF5, 0xE8, 0xB0, 0xEC, 0x1A, 0x0A, 0x46, 0x50, 0x92
};

/* Key hash for integrity verification */
const uint8_t PUBLIC_KEY_HASH[32] = {
    /* SHA-256 hash of public key - verify at build time */
};
